package lib.proguardprotect.utils

import java.io.File

/**
 * Parses R8/ProGuard mapping.txt files to extract class and member rename information.
 *
 * The mapping file format:
 * ```
 * original.ClassName -> obfuscated.Name:
 *     type originalMember -> obfuscatedMember
 *     1:2:returnType originalMethod(params) -> obfuscatedMethod
 * ```
 *
 * ## Usage
 * ```kotlin
 * val mapping = MappingParser.parse(File("mapping.txt"))
 * val classMapping = mapping["com.example.MyClass"]
 * if (classMapping != null && classMapping.obfuscatedName != "com.example.MyClass") {
 *     println("Class was renamed to ${classMapping.obfuscatedName}")
 * }
 * ```
 */
object MappingParser {

    /**
     * Represents a member (method or field) rename mapping.
     *
     * @property originalName The original name before R8 processing
     * @property obfuscatedName The name after R8 processing (may be same if kept)
     * @property type Either "method" or "field"
     */
    data class MemberMapping(
        val originalName: String,
        val obfuscatedName: String,
        val type: String
    )

    /**
     * Represents a class rename mapping including all its member mappings.
     *
     * @property originalName The original fully-qualified class name
     * @property obfuscatedName The name after R8 processing
     * @property members List of member (method/field) mappings for this class
     */
    data class ClassMapping(
        val originalName: String,
        val obfuscatedName: String,
        val members: MutableList<MemberMapping> = mutableListOf()
    )

    /**
     * Parses a mapping.txt file into a map of original class name → [ClassMapping].
     *
     * @param file The mapping.txt file generated by R8/ProGuard
     * @return Map keyed by original fully-qualified class name
     */
    fun parse(file: File): Map<String, ClassMapping> {
        val mappings = mutableMapOf<String, ClassMapping>()
        if (!file.exists()) return mappings

        var currentClass: ClassMapping? = null
        val classLinePattern = Regex("""^(\S+)\s+->\s+(\S+):$""")
        val memberPattern = Regex("""^\s+(?:\d+:\d+:)?(.+?)\s+(\S+)\s+->\s+(\S+)$""")

        file.forEachLine { line ->
            if (line.startsWith("#")) return@forEachLine

            val classMatch = classLinePattern.find(line)
            if (classMatch != null) {
                val original = classMatch.groupValues[1]
                val obfuscated = classMatch.groupValues[2]
                currentClass = ClassMapping(original, obfuscated)
                mappings[original] = currentClass!!
            } else {
                val memberMatch = memberPattern.find(line)
                if (memberMatch != null && currentClass != null) {
                    val originalName = memberMatch.groupValues[2]
                    val obfuscatedName = memberMatch.groupValues[3]
                    val simpleName = if (originalName.contains("(")) {
                        originalName.substringBefore("(")
                    } else {
                        originalName
                    }
                    val memberType = if (originalName.contains("(")) "method" else "field"
                    currentClass!!.members.add(MemberMapping(simpleName, obfuscatedName, memberType))
                }
            }
        }
        return mappings
    }
}
