package lib.proguardprotect

import lib.proguardprotect.analyzers.*
import lib.proguardprotect.models.ProguardIssue
import lib.proguardprotect.report.HtmlReportGenerator
import lib.proguardprotect.utils.MappingParser
import lib.proguardprotect.utils.MappingParser.ClassMapping
import lib.proguardprotect.utils.SourceScanner
import org.gradle.api.DefaultTask
import org.gradle.api.GradleException
import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.provider.ListProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.*
import java.io.File

/**
 * Primary analysis task for ProguardProtect — performs **post-build** analysis
 * of R8/ProGuard output artifacts to detect runtime crash vulnerabilities.
 *
 * ## Analysis Pipeline
 *
 * 1. **Build**: Task depends on `assemble{Variant}`, ensuring APK/AAB and mapping.txt exist
 * 2. **Parse mapping.txt**: Determines what R8 actually renamed, removed, or inlined
 * 3. **Inspect DEX**: Lists classes in the final DEX via `apkanalyzer` to verify class existence
 * 4. **Source pattern detection**: Runs analyzers on source code with **empty keep rules** to find
 *    ALL potentially vulnerable patterns (reflection, serialization, enum, callback, devirtualization)
 * 5. **Cross-reference**: Each detected pattern is validated against mapping.txt and DEX —
 *    only patterns where R8 actually renamed/removed the target are reported as issues
 * 6. **HTML report**: Generates a detailed HTML report with source code references,
 *    mapping details, and fix suggestions
 *
 * ## Why Post-Build?
 *
 * R8 behavior depends on code size, dependency graph, library versions, AGP version,
 * R8 mode (full vs compat), and optimization level. Pre-build source analysis against
 * keep rules can produce false positives. Post-build analysis checks what R8 **actually did**,
 * giving zero false positives.
 *
 * @see ProguardProtectPlugin Plugin registration and task wiring
 * @see HtmlReportGenerator Generates the HTML report
 */
abstract class PostBuildAnalysisTask : DefaultTask() {

    /** Path to mapping.txt generated by R8 during the release build. */
    @get:Internal
    abstract val mappingFile: RegularFileProperty

    /** Source directories to scan for vulnerable patterns. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val sourceDirs: ConfigurableFileCollection

    /** Asset directories to scan for JSON config files and other asset resources. */
    @get:InputFiles
    @get:PathSensitive(PathSensitivity.RELATIVE)
    abstract val assetsDirs: ConfigurableFileCollection

    /** ProGuard rules files (used for reference in reports, not for detection logic). */
    @get:Internal
    abstract val proguardFiles: ConfigurableFileCollection

    /** Whether to fail the build when errors are found. */
    @get:Input
    abstract val failOnError: Property<Boolean>

    /** Package prefixes to limit scanning scope (empty = scan all). */
    @get:Input
    abstract val targetPackages: ListProperty<String>

    /** Build variant name (e.g., "release"). */
    @get:Input
    abstract val variantName: Property<String>

    /** Output directory for generated reports. */
    @get:OutputDirectory
    abstract val reportDir: DirectoryProperty

    /** APK output directory — scanned for *.apk files at task execution time. */
    @get:Internal
    abstract val apkOutputDir: DirectoryProperty

    /** AAB output directory — scanned for *.aab files at task execution time. */
    @get:Internal
    abstract val aabOutputDir: DirectoryProperty

    /** Path to apkanalyzer binary from Android SDK (optional). */
    @get:Optional
    @get:Input
    abstract val apkAnalyzerPath: Property<String>

    init {
        group = "verification"
        description = "Analyzes release build artifacts for R8/ProGuard runtime crash vulnerabilities"
    }

    /**
     * Main analysis entry point. Executes the full post-build analysis pipeline:
     * parse mapping → inspect DEX → scan source patterns → cross-reference → generate report.
     */
    @TaskAction
    fun analyze() {
        val variant = variantName.get()
        logger.lifecycle("")
        logger.lifecycle("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        logger.lifecycle("  🛡️  ProguardProtect Post-Build Analysis — variant: $variant")
        logger.lifecycle("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

        // Step 1: Parse mapping.txt
        val mappingFileObj = mappingFile.get().asFile
        if (!mappingFileObj.exists()) {
            logger.warn("  ⚠️  mapping.txt not found at ${mappingFileObj.path}. Skipping analysis.")
            return
        }
        val mapping = MappingParser.parse(mappingFileObj)
        logger.lifecycle("  📋 Parsed mapping.txt: ${mapping.size} class mappings")

        // Step 2: Inspect DEX classes from APK/AAB
        val dexClasses = getDexClasses()
        if (dexClasses.isNotEmpty()) {
            logger.lifecycle("  📦 Found ${dexClasses.size} classes in DEX")
        }

        // Step 3: Scan source code for vulnerable patterns (with empty rules = find everything)
        val scanner = SourceScanner()
        val allSources = sourceDirs.files
            .filter { it.exists() }
            .flatMap { scanner.scanDirectory(it) }

        val packages = targetPackages.get()
        val filteredSources = if (packages.isEmpty()) allSources
        else allSources.filter { s -> packages.any { s.packageName.startsWith(it) } }

        logger.lifecycle("  📂 Scanned ${filteredSources.size} source files")

        val analyzers = listOf(
            ReflectionClassAnalyzer(),
            ReflectionMethodAnalyzer(),
            SerializationAnalyzer(),
            EnumAnalyzer(),
            CallbackAnalyzer(),
            DevirtualizationAnalyzer(),
            GsonTypeTokenAnalyzer(),
            CompanionObjectAnalyzer(),
            SealedClassAnalyzer(),
            AnnotationAnalyzer(),
            ParcelableAnalyzer(),
            JavascriptInterfaceAnalyzer(),
            NativeMethodAnalyzer(),
            WorkManagerAnalyzer(),
            CustomViewAnalyzer(),
            KotlinObjectAnalyzer(),
            ResourceNameAnalyzer(),
            GenericSignatureAnalyzer(),
            ComponentNameAnalyzer(),
            DataClassMemberAnalyzer(),
            DynamicProxyAnalyzer(),
            JsonAssetResourceAnalyzer(),
            FragmentClassAnalyzer(),
            SerializableAnalyzer()
        )

        // Run analyzers with EMPTY keep rules to find ALL potentially vulnerable patterns
        val emptyRules = emptyList<lib.proguardprotect.utils.KeepRule>()
        val allPotentialIssues = mutableListOf<ProguardIssue>()
        for (analyzer in analyzers) {
            val issues = analyzer.analyze(filteredSources, emptyRules)
            allPotentialIssues.addAll(issues)
        }
        logger.lifecycle("  🔍 Source analysis: ${allPotentialIssues.size} potentially vulnerable patterns found")

        // Step 4: Cross-reference each pattern with mapping.txt + DEX
        val confirmedIssues = crossReferenceWithMapping(allPotentialIssues, mapping, dexClasses)
        logger.lifecycle("  ✓  Post-build confirmation: ${confirmedIssues.size} confirmed issues")

        // Step 5: Generate reports
        val reportDirFile = reportDir.get().asFile
        reportDirFile.mkdirs()

        // HTML report
        val htmlReport = reportDirFile.resolve("proguard-protect-$variant.html")
        val generator = HtmlReportGenerator()
        generator.generate(
            outputFile = htmlReport,
            variant = variant,
            issues = confirmedIssues,
            mapping = mapping,
            sourceDirs = sourceDirs.files.toList(),
            buildArtifact = getBuildArtifactPath()
        )

        // Plain text report
        val textReport = reportDirFile.resolve("proguard-protect-$variant.txt")
        textReport.writeText(buildTextReport(variant, confirmedIssues))

        // Summary
        val errors = confirmedIssues.count { it.severity == ProguardIssue.Severity.ERROR }
        val warnings = confirmedIssues.count { it.severity == ProguardIssue.Severity.WARNING }

        logger.lifecycle("")
        logger.lifecycle("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
        if (confirmedIssues.isEmpty()) {
            logger.lifecycle("  ✅ No R8 runtime crash vulnerabilities detected!")
        } else {
            logger.lifecycle("  ⚠️  Found $errors error(s), $warnings warning(s)")
            logger.lifecycle("")
            confirmedIssues.forEach { issue ->
                logger.lifecycle("  ${issue}")
                logger.lifecycle("")
            }
        }
        logger.lifecycle("  📊 HTML Report: ${htmlReport.absolutePath}")
        logger.lifecycle("  📄 Text Report: ${textReport.absolutePath}")
        logger.lifecycle("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")

        if (errors > 0 && failOnError.get()) {
            throw GradleException(
                "ProguardProtect found $errors confirmed runtime crash vulnerability(ies). " +
                    "See HTML report: ${htmlReport.absolutePath}"
            )
        }
    }

    /**
     * Cross-references source-level vulnerability patterns with actual R8 mapping data
     * to confirm which issues are real (R8 actually renamed/removed the target).
     *
     * For each potential issue from source analysis:
     * - Looks up the target class in mapping.txt
     * - Checks if class was renamed or removed
     * - For member-level issues (methods/fields), checks if the specific member was renamed
     * - For devirtualization, confirms the class pattern exists in the build
     * - Verifies with DEX class list if available
     *
     * @param potentialIssues Issues found by source-level pattern analysis
     * @param mapping Parsed mapping.txt data (class → obfuscated name + members)
     * @param dexClasses Set of fully-qualified class names found in the final DEX
     * @return List of confirmed issues where R8 actually broke something
     */
    private fun crossReferenceWithMapping(
        potentialIssues: List<ProguardIssue>,
        mapping: Map<String, ClassMapping>,
        dexClasses: Set<String>
    ): List<ProguardIssue> {
        val confirmed = mutableListOf<ProguardIssue>()
        val seenKeys = mutableSetOf<String>()

        for (issue in potentialIssues) {
            val className = issue.className ?: continue
            val dedupeKey = "${issue.type}:$className:${issue.memberName ?: ""}"
            if (!seenKeys.add(dedupeKey)) continue

            val mappingEntry = mapping[className]

            // Devirtualization: class must exist in the build and NOT be fully protected by keep rules.
            // Note: this is a code-level issue. The real fix is to override the method in the subclass.
            // Keep rules prevent class renaming but do NOT prevent R8 from devirtualizing calls.
            // We confirm this issue if the class exists in the build regardless of keep rules,
            // since keep rules do not stop R8's devirtualization optimizations.
            if (issue.type == ProguardIssue.IssueType.DEVIRTUALIZATION_ILLEGAL_ACCESS) {
                // Confirm class exists in mapping (meaning it was compiled and processed by R8)
                val classInBuild = mappingEntry != null || (dexClasses.isNotEmpty() && className in dexClasses)
                if (classInBuild || mapping.isNotEmpty()) {
                    val classRenamed = mappingEntry != null && mappingEntry.obfuscatedName != className.replace('.', '/')
                        && mappingEntry.obfuscatedName != className
                    val renamedNote = if (classRenamed) " Class was renamed → '${mappingEntry?.obfuscatedName}'."
                                      else " Class name preserved (keep rule applied)."
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED]$renamedNote ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For RESOURCE_SHRUNK_BY_NAME: check if the named resource actually exists in APK/AAB.
            // The className here is the source package (not a Java class), so skip mapping lookup.
            if (issue.type == ProguardIssue.IssueType.RESOURCE_SHRUNK_BY_NAME) {
                val memberName = issue.memberName ?: continue
                if (memberName == "dynamic_getIdentifier") {
                    // Dynamic name — can't statically verify, keep as warning
                    continue
                }
                val parts = memberName.split("/")
                if (parts.size == 2) {
                    val resType = parts[0]
                    val resName = parts[1]
                    if (!resourceExistsInArtifact(resType, resName)) {
                        confirmed.add(issue.copy(
                            message = "[POST-BUILD CONFIRMED] Resource '$resName' (type: $resType) is absent from the " +
                                "final APK/AAB — aapt2 removed it during resource shrinking. ${issue.message}",
                            severity = ProguardIssue.Severity.ERROR
                        ))
                    }
                }
                continue
            }

            // For JSON_ASSET_RESOURCE_STRIPPED: assets/*.json → resources referenced in JSON files
            // scan the actual JSON files in assets and verify each resource name against resources.txt
            if (issue.type == ProguardIssue.IssueType.JSON_ASSET_RESOURCE_STRIPPED) {
                val memberName = issue.memberName ?: continue
                if (memberName == "json_dynamic_getIdentifier") {
                    // Dynamic path — can't statically verify JSON content, keep as warning
                    continue
                }
                if (memberName.startsWith("json_asset:")) {
                    val jsonFileName = memberName.removePrefix("json_asset:")
                    // Find the JSON file in asset directories first, then source directories
                    val jsonFile = (assetsDirs.files + sourceDirs.files)
                        .flatMap { dir -> dir.walkTopDown().filter { it.name == jsonFileName.substringAfterLast("/") } }
                        .firstOrNull()
                    if (jsonFile != null && jsonFile.exists()) {
                        val missingResources = findMissingJsonResources(jsonFile)
                        if (missingResources.isNotEmpty()) {
                            confirmed.add(issue.copy(
                                message = "[POST-BUILD CONFIRMED] ${missingResources.size} resource(s) referenced in " +
                                    "'$jsonFileName' are absent from the final APK/AAB — aapt2 removed them during " +
                                    "strict resource shrinking. Missing: ${missingResources.joinToString(", ")}. " +
                                    "${issue.message}",
                                severity = ProguardIssue.Severity.ERROR
                            ))
                        }
                    }
                }
                continue
            }

            // For GENERIC_SIGNATURE_STRIPPED: the actual fix is -keepattributes Signature.
            // We check the raw ProGuard rule files for the keepattributes directive.
            // No DEX check needed — the Signature attribute is stripped globally whenever
            // -keepattributes Signature is absent, affecting all classes that use
            // genericSuperclass/ParameterizedType for runtime generic type introspection.
            if (issue.type == ProguardIssue.IssueType.GENERIC_SIGNATURE_STRIPPED) {
                val hasSignatureKeep = proguardFiles.files.any { f ->
                    if (!f.exists()) return@any false
                    // Parse multi-line -keepattributes directives:
                    // AGP's default file uses indented continuation lines, e.g.:
                    //   -keepattributes AnnotationDefault,
                    //                   Signature
                    // We join continuation lines (non-comment lines that don't start with '-')
                    // to handle both single-line and multi-line forms.
                    val lines = f.readLines()
                    val joined = StringBuilder()
                    for (line in lines) {
                        val stripped = line.replace(Regex("#.*$"), "").trim()
                        if (stripped.isEmpty()) continue
                        if (stripped.startsWith("-")) {
                            joined.append("\n").append(stripped)
                        } else {
                            // Continuation line — join to previous
                            joined.append(" ").append(stripped)
                        }
                    }
                    Regex("""-keepattributes\b[^\n]*\bSignature\b""").containsMatchIn(joined.toString())
                }
                if (!hasSignatureKeep) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] '-keepattributes Signature' is absent from ProGuard rules. " +
                            "R8 strips the Signature bytecode attribute from ALL classes — including '$className'. " +
                            "genericSuperclass returns raw Class instead of ParameterizedType → ClassCastException at runtime. " +
                            "${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }


            if (mappingEntry == null) {
                // Class not in mapping at all — could mean R8 removed it entirely
                // Verify via DEX if available
                if (dexClasses.isNotEmpty()) {
                    val dexName = className.replace('.', '/')
                    val foundInDex = dexClasses.any { it == className || it == "L$dexName;" }
                    if (!foundInDex && className.startsWith("app.")) {
                        confirmed.add(issue.copy(
                            message = "[POST-BUILD CONFIRMED] Class '$className' not found in final DEX — " +
                                "R8 removed it entirely. ${issue.message}",
                            severity = ProguardIssue.Severity.ERROR
                        ))
                    }
                }
                continue
            }

            val wasRenamed = mappingEntry.obfuscatedName != className

            // For REFLECTION_METHOD_ACCESS: check if specific member was renamed or removed
            // Note: class rename alone doesn't matter here — reflection is on a live instance,
            // not via Class.forName. Only member rename/removal breaks getDeclaredMethod/getDeclaredField.
            if (issue.type == ProguardIssue.IssueType.REFLECTION_METHOD_ACCESS && issue.memberName != null) {
                val memberMapping = mappingEntry.members.firstOrNull { m ->
                    m.originalName == issue.memberName
                }
                if (memberMapping != null && memberMapping.obfuscatedName != issue.memberName) {
                    // Member was renamed
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed member '${issue.memberName}' → '${memberMapping.obfuscatedName}' " +
                            "in class '$className'. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                } else if (memberMapping == null) {
                    // Member name not found in mapping — could mean:
                    // a) R8 removed it, OR
                    // b) The captured name is a variable name, not the actual member name
                    //    (e.g., analyzer captured 'fieldNames' variable instead of 'serverUrl' field)
                    // Check if most members were preserved (suggesting -keepclassmembers is in effect)
                    val totalMembers = mappingEntry.members.size
                    val preservedMembers = mappingEntry.members.count { m -> m.obfuscatedName == m.originalName }
                    val mostMembersPreserved = totalMembers > 0 && preservedMembers.toDouble() / totalMembers > 0.7

                    if (!mostMembersPreserved) {
                        // Members were generally renamed — this member was likely renamed/removed too
                        confirmed.add(issue.copy(
                            message = "[POST-BUILD CONFIRMED] R8 removed/inlined member '${issue.memberName}' " +
                                "from class '$className' (class mapped → '${mappingEntry.obfuscatedName}'). ${issue.message}",
                            severity = ProguardIssue.Severity.ERROR
                        ))
                    }
                    // If most members preserved, -keepclassmembers is likely in effect → safe
                }
                // If member exists with same name → member is kept, no issue (even if class renamed)
                continue
            }

            // For SERIALIZATION_FIELD_RENAME: check if any fields were renamed
            if (issue.type == ProguardIssue.IssueType.SERIALIZATION_FIELD_RENAME) {
                val fieldsRenamed = mappingEntry.members.any { m ->
                    m.type == "field" && m.obfuscatedName != m.originalName
                }
                val classAffected = wasRenamed || fieldsRenamed
                if (classAffected) {
                    val detail = when {
                        wasRenamed && fieldsRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}' AND renamed fields"
                        wasRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'"
                        else -> "R8 renamed fields in '$className'"
                    }
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] $detail. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For GSON_TYPE_TOKEN_STRIPPED: model class renamed or fields renamed → TypeToken will fail
            if (issue.type == ProguardIssue.IssueType.GSON_TYPE_TOKEN_STRIPPED) {
                val fieldsRenamed = mappingEntry.members.any { m ->
                    m.type == "field" && m.obfuscatedName != m.originalName
                }
                if (wasRenamed || fieldsRenamed) {
                    val detail = when {
                        wasRenamed && fieldsRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}' AND renamed fields"
                        wasRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'"
                        else -> "R8 renamed fields in '$className'"
                    }
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] $detail. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For COMPANION_OBJECT_STRIPPED: companion class renamed or missing → reflection fails
            if (issue.type == ProguardIssue.IssueType.COMPANION_OBJECT_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed companion class '$className' → '${mappingEntry.obfuscatedName}'. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                } else if (dexClasses.isNotEmpty()) {
                    val dexName = className.replace('.', '/').replace('$', '$')
                    val foundInDex = dexClasses.any { it == className || it.contains(className.substringAfterLast(".")) }
                    if (!foundInDex) {
                        confirmed.add(issue.copy(
                            message = "[POST-BUILD CONFIRMED] Companion class '$className' not found in final DEX — R8 removed it. ${issue.message}",
                            severity = ProguardIssue.Severity.ERROR
                        ))
                    }
                }
                continue
            }

            // For SEALED_SUBCLASS_STRIPPED: check if any expected subtypes are missing from DEX
            if (issue.type == ProguardIssue.IssueType.SEALED_SUBCLASS_STRIPPED) {
                val subtypeNames = issue.memberName?.split(",")?.map { it.trim() }?.filter { it.isNotEmpty() }
                if (!subtypeNames.isNullOrEmpty() && dexClasses.isNotEmpty()) {
                    val missingSubtypes = subtypeNames.filter { subtypeFqn ->
                        val dexFormat = subtypeFqn.replace('.', '/')
                        !dexClasses.any { it == subtypeFqn || it == "L$dexFormat;" || it.endsWith(subtypeFqn.substringAfterLast(".")) }
                    }
                    if (missingSubtypes.isNotEmpty()) {
                        confirmed.add(issue.copy(
                            message = "[POST-BUILD CONFIRMED] R8 removed ${missingSubtypes.size} sealed subtype(s) of '$className' from DEX: " +
                                "${missingSubtypes.joinToString(", ")}. ${issue.message}",
                            severity = ProguardIssue.Severity.ERROR
                        ))
                    }
                } else if (wasRenamed) {
                    // Sealed class itself was renamed → subtypes likely renamed/removed too
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed sealed class '$className' → '${mappingEntry.obfuscatedName}'. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For ANNOTATION_STRIPPED: annotation class renamed in mapping → stripped at runtime
            if (issue.type == ProguardIssue.IssueType.ANNOTATION_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed annotation class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "getAnnotation() will return null at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For PARCELABLE_CLASS_RENAMED: class renamed → Bundle deserialization fails
            if (issue.type == ProguardIssue.IssueType.PARCELABLE_CLASS_RENAMED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed Parcelable class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "Android stores original class name in Parcel → BadParcelableException on deserialization. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For JAVASCRIPT_INTERFACE_STRIPPED: class renamed → @JavascriptInterface methods renamed
            if (issue.type == ProguardIssue.IssueType.JAVASCRIPT_INTERFACE_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "@JavascriptInterface methods are renamed → JavaScript bridge calls fail at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For NATIVE_METHOD_RENAMED: class renamed → JNI signatures no longer match
            if (issue.type == ProguardIssue.IssueType.NATIVE_METHOD_RENAMED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "JNI function signatures encode the original class name → UnsatisfiedLinkError at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For WORKMANAGER_WORKER_STRIPPED: class renamed → WorkManager ClassNotFoundException
            if (issue.type == ProguardIssue.IssueType.WORKMANAGER_WORKER_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed Worker class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "WorkManager stores original FQCN in DB → ClassNotFoundException on execution. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For CUSTOM_VIEW_STRIPPED: class renamed → LayoutInflater ClassNotFoundException
            if (issue.type == ProguardIssue.IssueType.CUSTOM_VIEW_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed custom View class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "LayoutInflater uses original class name from XML → InflateException: ClassNotFoundException. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For KOTLIN_OBJECT_INSTANCE_REMOVED: class renamed OR INSTANCE field renamed away
            if (issue.type == ProguardIssue.IssueType.KOTLIN_OBJECT_INSTANCE_REMOVED) {
                // mapping.txt only lists RENAMED entries. Absence of INSTANCE means it was
                // preserved (not renamed), NOT that it was removed. We check:
                // 1. Class was renamed → Class.forName() / objectInstance will fail
                // 2. INSTANCE field was renamed to something else (appears with different obfuscated name)
                val instanceFieldRenamed = mappingEntry.members.any { m ->
                    m.originalName == "INSTANCE" && m.obfuscatedName != "INSTANCE"
                }
                // Also flag if class is NOT in DEX at all (removed entirely)
                val classRemovedFromDex = !dexClasses.contains(mappingEntry.obfuscatedName)
                if (wasRenamed || instanceFieldRenamed || classRemovedFromDex) {
                    val detail = when {
                        wasRenamed && instanceFieldRenamed ->
                            "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}' AND removed INSTANCE field"
                        classRemovedFromDex ->
                            "R8 removed class '$className' entirely from DEX"
                        wasRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'"
                        else -> "R8 renamed INSTANCE field in class '$className'"
                    }
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] $detail. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For COMPONENT_CLASS_NOT_FOUND: component (Activity/Service) class renamed → string ref stale
            if (issue.type == ProguardIssue.IssueType.COMPONENT_CLASS_NOT_FOUND) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed component class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "ComponentName/setClassName uses original string → ActivityNotFoundException at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For DATA_CLASS_MEMBER_STRIPPED: class renamed or copy()/componentN() methods removed
            if (issue.type == ProguardIssue.IssueType.DATA_CLASS_MEMBER_STRIPPED) {
                val copyMethodRemoved = mappingEntry.members.none { m ->
                    m.originalName == "copy" || m.originalName.startsWith("component")
                }
                if (wasRenamed || copyMethodRemoved) {
                    val detail = when {
                        wasRenamed && copyMethodRemoved ->
                            "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}' AND removed copy()/componentN() methods"
                        wasRenamed -> "R8 renamed class '$className' → '${mappingEntry.obfuscatedName}'"
                        else -> "R8 removed copy()/componentN() methods from '$className'"
                    }
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] $detail. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For DYNAMIC_PROXY_STRIPPED: interface renamed → Proxy dispatch fails
            if (issue.type == ProguardIssue.IssueType.DYNAMIC_PROXY_STRIPPED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed interface '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "InvocationHandler dispatch uses original method names → IllegalArgumentException or " +
                            "AbstractMethodError at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For FRAGMENT_CLASS_RENAMED: Fragment subclass renamed → back stack restoration fails
            if (issue.type == ProguardIssue.IssueType.FRAGMENT_CLASS_RENAMED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed Fragment class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "FragmentManager persists the original FQCN in saved instance state. " +
                            "On activity recreation (rotation/process death), FragmentFactory.instantiate() " +
                            "looks up '$className' which no longer exists → ClassNotFoundException. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For SERIALIZABLE_CLASS_RENAMED: class renamed → cross-build deserialization fails
            if (issue.type == ProguardIssue.IssueType.SERIALIZABLE_CLASS_RENAMED) {
                if (wasRenamed) {
                    confirmed.add(issue.copy(
                        message = "[POST-BUILD CONFIRMED] R8 renamed Serializable class '$className' → '${mappingEntry.obfuscatedName}'. " +
                            "The serialized byte stream embeds the class FQCN. Any data serialized by a " +
                            "differently-obfuscated or unobfuscated build cannot be deserialized → " +
                            "ClassNotFoundException or InvalidClassException at runtime. ${issue.message}",
                        severity = ProguardIssue.Severity.ERROR
                    ))
                }
                continue
            }

            // For all other class-level issues: check if class was renamed
            if (wasRenamed) {
                confirmed.add(issue.copy(
                    message = "[POST-BUILD CONFIRMED] R8 renamed '$className' → '${mappingEntry.obfuscatedName}'. ${issue.message}",
                    severity = ProguardIssue.Severity.ERROR
                ))
            }
        }

        return confirmed
    }

    /**
     * Finds the first APK file in the APK output directory.
     * Handles any naming convention (custom archivesName, applicationId, etc.).
     */
    private fun findApk(): File? {
        if (!apkOutputDir.isPresent) return null
        val dir = apkOutputDir.get().asFile
        if (!dir.exists()) return null
        return dir.listFiles()?.filter { it.extension == "apk" }?.firstOrNull()
    }

    /**
     * Finds the first AAB file in the AAB output directory.
     */
    private fun findAab(): File? {
        if (!aabOutputDir.isPresent) return null
        val dir = aabOutputDir.get().asFile
        if (!dir.exists()) return null
        return dir.listFiles()?.filter { it.extension == "aab" }?.firstOrNull()
    }

    /**
     * Checks whether a named resource (e.g. `promo_banner` drawable) exists in the final APK/AAB.
     * Used to post-build confirm [ProguardIssue.IssueType.RESOURCE_SHRUNK_BY_NAME] issues.
     *
     * Resources removed by aapt2's shrinkResources will not have any entry in the artifact's
     * zip contents for their `res/type/name` path.
     *
     * @param resourceType Resource type string, e.g. "drawable", "layout", "string"
     * @param resourceName Resource name without extension, e.g. "promo_banner"
     * @return `true` if the resource was found in the artifact, `false` if removed/absent
     */
    /**
     * Checks if a resource exists in the final build artifact.
     *
     * Priority: Check `resources.txt` (generated by aapt2's resource shrinker) first,
     * since AGP 9+ obfuscates resource file names in the APK/AAB zip entries, making
     * zip-based lookup unreliable. Falls back to zip inspection for older AGP versions.
     *
     * @param resourceType Resource type (e.g. "drawable")
     * @param resourceName Resource name without extension (e.g. "promo_banner")
     * @return true if the resource exists in the final artifact, false if removed
     */
    private fun resourceExistsInArtifact(resourceType: String, resourceName: String): Boolean {
        // Primary: check resources.txt (generated alongside mapping.txt by aapt2 shrinker)
        // Format: "drawable:name:id reachable from ..." or "drawable:name:id unused"
        val mappingDir = mappingFile.get().asFile.parentFile
        val resourcesReport = File(mappingDir, "resources.txt")
        if (resourcesReport.exists()) {
            return resourceExistsInResourcesReport(resourcesReport, resourceType, resourceName)
        }

        // Fallback: zip inspection (unreliable on AGP 9+ due to resource name obfuscation)
        val apk = findApk()
        if (apk != null && apk.exists()) {
            if (resourceExistsInZip(apk, resourceType, resourceName, "")) return true
        }
        val aab = findAab()
        if (aab != null && aab.exists()) {
            if (resourceExistsInZip(aab, resourceType, resourceName, "base/")) return true
        }
        // If neither artifact found, assume resource exists (avoid false positive)
        return apk == null && aab == null
    }

    /**
     * Checks if a resource is marked as reachable in the aapt2 resource shrink report.
     *
     * The `resources.txt` file (generated at `build/outputs/mapping/<variant>/resources.txt`)
     * lists every resource with its reachability status:
     * - `drawable:promo_banner:2131034134 reachable from keep xml file` → resource kept
     * - No entry or `... unused` → resource was removed by aapt2 strict mode
     *
     * @param resourcesReport The `resources.txt` file
     * @param resourceType Resource type folder (e.g. "drawable")
     * @param resourceName Resource name without extension (e.g. "promo_banner")
     * @return true if the resource is reachable (kept), false if absent or unused
     */
    private fun resourceExistsInResourcesReport(
        resourcesReport: File,
        resourceType: String,
        resourceName: String
    ): Boolean {
        return try {
            resourcesReport.bufferedReader().use { reader ->
                reader.lineSequence().any { line ->
                    // Match lines like: "drawable:promo_banner:... reachable from ..."
                    // Avoid "is not reachable." which also contains "reachable"
                    line.startsWith("$resourceType:$resourceName:") && line.contains("reachable from")
                }
            }
        } catch (e: Exception) {
            logger.warn("ProguardProtect: Could not read resources.txt: ${e.message}")
            true // Assume exists on error to avoid false positive
        }
    }


    /**
     * Checks if a resource file exists inside a zip artifact (APK or AAB).
     * Fallback for when resources.txt is unavailable (older AGP).
     * Note: AGP 9+ obfuscates resource file names, making this unreliable.
     *
     * @param artifact The APK or AAB zip file
     * @param resourceType Resource type (e.g. "drawable")
     * @param resourceName Resource name without extension (e.g. "promo_banner")
     * @param prefix Path prefix inside zip ("" for APK, "base/" for AAB)
     */
    private fun resourceExistsInZip(
        artifact: File,
        resourceType: String,
        resourceName: String,
        prefix: String
    ): Boolean {
        return try {
            java.util.zip.ZipFile(artifact).use { zip ->
                val entries = zip.entries().toList()
                entries.any { entry ->
                    val path = entry.name
                    path.startsWith("${prefix}res/$resourceType") &&
                        (path.contains("/$resourceName.") || path.endsWith("/$resourceName"))
                }
            }
        } catch (e: Exception) {
            logger.warn("ProguardProtect: Could not inspect artifact ${artifact.name} for resource check: ${e.message}")
            true // Assume exists on error to avoid false positive
        }
    }

    /**
     * Scans a JSON asset file for string values that look like Android resource names,
     * then checks each against [resourceExistsInArtifact] to find which ones were shrunk away.
     *
     * @param jsonFile The JSON asset file to scan
     * @return List of "type/name" strings for resources that are absent from the final artifact
     */
    private fun findMissingJsonResources(jsonFile: File): List<String> {
        val missing = mutableListOf<String>()
        try {
            val content = jsonFile.readText()
            // Extract all quoted string values from the JSON (any depth)
            val stringValuePattern = Regex(""""([a-z][a-z0-9_]{2,49})"""")
            val resourceNamePattern = Regex("""^[a-z][a-z0-9_]{2,49}$""")
            val candidates = stringValuePattern.findAll(content)
                .map { it.groupValues[1] }
                .filter { resourceNamePattern.matches(it) }
                .toSet()

            // Check against each common drawable/string resource type
            val resourceTypes = listOf("drawable", "mipmap", "string", "layout", "raw")
            val mappingDir = mappingFile.get().asFile.parentFile
            val resourcesReport = File(mappingDir, "resources.txt")

            if (resourcesReport.exists()) {
                // Read resources.txt once and search for each candidate
                val resourcesContent = resourcesReport.readText()
                for (candidate in candidates) {
                    for (resType in resourceTypes) {
                        val isReachable = resourcesContent.lines().any { line ->
                            line.startsWith("$resType:$candidate:") && line.contains("reachable from")
                        }
                        val isPresent = resourcesContent.lines().any { line ->
                            line.startsWith("$resType:$candidate:")
                        }
                        if (isPresent && !isReachable) {
                            missing.add("$resType/$candidate")
                            break // Don't double-report same name across types
                        }
                    }
                }
            }
        } catch (e: Exception) {
            logger.warn("ProguardProtect: Could not scan JSON asset file ${jsonFile.name}: ${e.message}")
        }
        return missing
    }

    /**
     * Retrieves the set of class names present in the final DEX files of the APK/AAB.
     *
     * @return Set of fully-qualified class names, or empty set if tools unavailable
     */
    private fun getDexClasses(): Set<String> {
        // Try APK with apkanalyzer first (most reliable)
        val apk = findApk()
        if (apk != null && apkAnalyzerPath.isPresent) {
            val result = runApkAnalyzer(apk)
            if (result.isNotEmpty()) return result
        }

        // For AAB: extract DEX from the zip and use dexdump
        val aab = findAab()
        if (aab != null) {
            val result = extractDexClassesFromAab(aab)
            if (result.isNotEmpty()) return result
        }

        // Fallback: try apkanalyzer on AAB (limited support)
        if (aab != null && apkAnalyzerPath.isPresent) {
            val result = runApkAnalyzer(aab)
            if (result.isNotEmpty()) return result
        }

        return emptySet()
    }

    /**
     * Runs apkanalyzer to list DEX classes from an APK file.
     */
    private fun runApkAnalyzer(artifact: File): Set<String> {
        val analyzerPath = apkAnalyzerPath.get()
        return try {
            val process = ProcessBuilder(analyzerPath, "dex", "packages", artifact.absolutePath)
                .redirectErrorStream(true).start()
            val output = process.inputStream.bufferedReader().readText()
            process.waitFor()
            val classPattern = Regex("""^C\s+\w+\s+\d+\s+\d+\s+\d+\s+(\S+)""", RegexOption.MULTILINE)
            val classes = classPattern.findAll(output).map { it.groupValues[1] }.toSet()
            if (classes.isEmpty()) {
                logger.info("  ℹ️  apkanalyzer returned no classes for ${artifact.name}")
            }
            classes
        } catch (e: Exception) {
            logger.warn("  ⚠️  apkanalyzer failed for ${artifact.name}: ${e.message}")
            emptySet()
        }
    }

    /**
     * Extracts DEX files from an AAB (zip), then uses dexdump to list classes.
     * AAB structure: base/dex/classes.dex, base/dex/classes2.dex, etc.
     */
    private fun extractDexClassesFromAab(aabFile: File): Set<String> {
        // Locate dexdump from Android SDK build-tools
        val androidHome = System.getenv("ANDROID_HOME")
            ?: System.getenv("ANDROID_SDK_ROOT")
            ?: "${System.getProperty("user.home")}/Library/Android/sdk"
        val buildToolsDir = File(androidHome, "build-tools")
        val dexdumpPath = buildToolsDir.listFiles()
            ?.filter { it.isDirectory }
            ?.sortedDescending()
            ?.map { File(it, "dexdump") }
            ?.firstOrNull { it.exists() }
            ?: return emptySet()

        val tempDir = File.createTempFile("proguardprotect-aab-", "").also {
            it.delete(); it.mkdirs()
        }

        return try {
            // Extract dex files from AAB
            val unzip = ProcessBuilder("unzip", "-o", "-q", aabFile.absolutePath, "base/dex/*", "-d", tempDir.absolutePath)
                .redirectErrorStream(true).start()
            unzip.waitFor()

            val dexDir = File(tempDir, "base/dex")
            if (!dexDir.exists()) return emptySet()

            val classes = mutableSetOf<String>()
            val classPattern = Regex("""Class descriptor\s+:\s+'L([^']+);'""")

            dexDir.listFiles()?.filter { it.extension == "dex" }?.forEach { dexFile ->
                val process = ProcessBuilder(dexdumpPath.absolutePath, "-f", dexFile.absolutePath)
                    .redirectErrorStream(true).start()
                val output = process.inputStream.bufferedReader().readText()
                process.waitFor()
                classPattern.findAll(output).forEach { match ->
                    classes.add(match.groupValues[1].replace('/', '.'))
                }
            }
            classes
        } catch (e: Exception) {
            logger.warn("  ⚠️  Could not extract DEX classes from AAB: ${e.message}")
            emptySet()
        } finally {
            tempDir.deleteRecursively()
        }
    }

    /**
     * Returns the path to the primary build artifact (APK or AAB) for display in reports.
     */
    private fun getBuildArtifactPath(): String {
        return (findApk() ?: findAab())?.absolutePath ?: "N/A"
    }

    /**
     * Generates a plain-text report of confirmed issues.
     */
    private fun buildTextReport(variant: String, issues: List<ProguardIssue>): String {
        val sb = StringBuilder()
        sb.appendLine("ProguardProtect Post-Build Analysis Report")
        sb.appendLine("Variant: $variant")
        sb.appendLine("=".repeat(70))
        sb.appendLine()
        if (issues.isEmpty()) {
            sb.appendLine("✅ No R8 runtime crash vulnerabilities detected.")
        } else {
            sb.appendLine("Found ${issues.size} confirmed issue(s):")
            sb.appendLine()
            issues.forEachIndexed { i, issue ->
                sb.appendLine("${i + 1}. $issue")
                sb.appendLine()
            }
        }
        return sb.toString()
    }
}
